#Height-Weight

##import library

In [27]:
from __future__ import print_function
from __future__ import division

In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
import joblib
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

##connect gdrive

In [3]:
from google.colab import drive

drive.mount('/content/gdrive')

Mounted at /content/gdrive


##dataset

In [5]:
%cd /content/gdrive/MyDrive/technical

/content/gdrive/MyDrive/technical


In [8]:
data = pd.read_csv('weight-height.csv')
data.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [11]:
data.Height.max()

78.9987423463896

In [12]:
data.info

<bound method DataFrame.info of       Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]>

In [13]:
# cek apakah ada null value
data.isnull().sum()

Gender    0
Height    0
Weight    0
dtype: int64

In [14]:
# cek dimensi dari dataset
data.shape

(10000, 3)

In [15]:
data.iloc[:, 1:]

Height      Weight
0     73.847017  241.893563
1     68.781904  162.310473
2     74.110105  212.740856
3     71.730978  220.042470
4     69.881796  206.349801
...         ...         ...
9995  66.172652  136.777454
9996  67.067155  170.867906
9997  63.867992  128.475319
9998  69.034243  163.852461
9999  61.944246  113.649103

[10000 rows x 2 columns]

##scaling & labeling

In [17]:
label_encoder_gender = LabelEncoder()

data.iloc[:,0] = label_encoder_gender.fit_transform(data.iloc[:,0])

In [18]:
data.head()

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

In [19]:
X = data.iloc[:, :-1].values
print(X)

[[ 1.         73.84701702]
 [ 1.         68.78190405]
 [ 1.         74.11010539]
 ...
 [ 0.         63.86799221]
 [ 0.         69.03424313]
 [ 0.         61.94424588]]


In [20]:
y = data.iloc[:, 2].values
print(y)

[241.89356318 162.31047252 212.74085556 ... 128.47531878 163.85246135
 113.64910268]


#training set & testing set

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 10)

##modeling

In [29]:
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [38]:
from joblib import dump

#menyimpan model & scaler

dump(regressor, "predict-weight.pkl")

['predict-weight.pkl']

In [32]:
# memprediksi test set

y_pred = regressor.predict(X_test)

In [33]:
# testing
X_test.shape

(2000, 2)

In [34]:
X_test

array([[ 1.        , 68.32145287],
       [ 0.        , 64.65471816],
       [ 1.        , 74.03459775],
       ...,
       [ 1.        , 67.55618322],
       [ 0.        , 63.921176  ],
       [ 1.        , 62.41843392]])

In [35]:
data = [[1, 56]]
tes = regressor.predict(data)
tes

array([108.96891748])

##cek akurasi

In [36]:
y_pred = regressor.predict(X_test)
print('Coefficients      : ', regressor.coef_)

print('Mean Squared Error: %.2f' % np.mean((regressor.predict(X_test)- y_test) ** 2))

print('Variance score    : %.2f' % regressor.score(X_test, y_test))

Coefficients      :  [19.22898618  5.98044901]
Mean Squared Error: 99.84
Variance score    : 0.91


In [37]:
from sklearn.metrics import r2_score,mean_squared_error
r2_score(y_test,y_pred)

0.9062628857795717